---
# handlers file for test
- name: Reload SSH
  service:
    name: sshd
    state: reloaded

- name: start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Reload systemd
  command: systemctl daemon-reload