---
- name: Create minecraft user
  user: name={{minecraft_user}} home={{ minecraft_home }} createhome=no system=yes shell=/bin/false

- name: Setup minecraft home
  file: path={{ minecraft_home }} state=directory owner={{minecraft_user}} group={{minecraft_user}}

- name: Install requiered packages
  include_tasks:
    file: install_packages.yml

- name: Download minecraft server
  get_url:
    url: "{{ minecraft_repo_url }}"
    dest: "{{ minecraft_home }}/{{ minecraft_jar_name }}"
