---
- name: Create minecraft user
  user: name={{ minecraft_user }} home={{ minecraft_home }} createhome=no system=yes shell=/bin/false

- name: Setup minecraft home
  file: path={{ minecraft_home }} state=directory owner={{ minecraft_user }} group={{minecraft_user}}

- name: Install requiered packages
  include_tasks:
    file: install_packages.yml

- name: Download minecraft server
  get_url:
    url: "{{ minecraft_repo_url }}"
    dest: "{{ minecraft_home }}/{{ minecraft_jar_name }}"

- name: Create minecraft server properties
  template: 
    src: server.properties.jinja
    dest: "{{ minecraft_home }}/server.properties"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"

- name: Copy EULA file
  copy: 
    src: minecraft-eula.txt
    dest: "{{ minecraft_home }}/eula.txt"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"

- name: Create minecraft systemd service
  template: 
    src: minecraft-server.service.jinja
    dest: /etc/systemd/system/minecraft-server.service 
    owner: root 
    group: root

- name: Create minecraft systemd start script
  template: 
    src: minecraft-server-start.sh.jinja
    dest: "{{ minecraft_home }}/minecraft-server-start.sh"
    owner: root
    group: root

- name: Create minecraft systemd stop script
  template: 
    src: minecraft-server-stop.sh.jinja
    dest: "{{ minecraft_home }}/minecraft-server-stop.sh"
    owner: root
    group: root

- name: Add minecraft port to internal zone in firewall
  firewalld:
    zone: public
    port: "{{ minecraft_port }}/tcp"
    state: enabled
    immediate: true
    permanent: true

- name: Start Minecraft server
  service:
    name: minecraft-server
    enabled: yes
    state: started
