---
- name: Perform full patching
  package:
    name: '*'
    state: latest
    
- name: Install yum packages list {{ yum_packages_to_install | join(' ') }}
  yum:
    name: "{{ yum_packages_to_install }}"

- name: Upload python requierements file
  copy:
    dest: "{{ requirements_file_path }}"
    src: etc/tmp/requirements_python.txt
    owner: root
    group: root
    mode: 0644

- name: Install python requiered packages
  pip:
    requirements: "{{ requirements_file_path }}"