---
- name: Perform full patching
  yum:
    name: '*'
    state: latest
    autoremove: true

- name: Install yum packages list {{ yum_packages_to_install | join(' ') }}
  yum:
    name: "{{ yum_packages_to_install }}"

- name: Upload python requierements file
  copy:
    dest: "{{ python_requirements_file_path }}"
    src: files/requirements_python.txt
    owner: root
    group: root
    mode: 0644

- name: Install python requiered packages
  pip:
    requirements: "{{ python_requirements_file_path }}"

- name: Remove python requirements file
  ansible.builtin.file:
    path: "{{ python_requirements_file_path }}"
    state: absent
