---
- name: Perform full patching
  dnf:
    name: '*'
    state: latest
    skip_broken: true

- name: Remove unused packages
  dnf:
    autoremove: true

- name: Install dnf packages list {{ dnf_packages_to_install | join(' ') }}
  dnf:
    name: "{{ dnf_packages_to_install }}"

- name: Upload python requierements file
  copy:
    dest: "{{ python_requirements_file_path }}"
    src: files/requirements_python.txt
    owner: root
    group: root
    mode: 0644

- name: Install python requiered packages
  pip:
    requirements: "{{ python_requirements_file_path }}"

- name: Remove python requirements file
  ansible.builtin.file:
    path: "{{ python_requirements_file_path }}"
    state: absent
