---
- name: Add HTTP port to public zone
  firewalld:
    zone: public
    service: http
    state: enabled
    immediate: true
    permanent: true

- name: Add HTTPS port to public zone
  firewalld:
    zone: public
    service: https
    state: enabled
    immediate: true
    permanent: true
