---
- name: Upload Jail Rules
  copy:
    dest: /etc/fail2ban/jail.local
    src: etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: true
