---
- name: Upload galaxy requirements file
  copy:
    dest: "{{ galaxy_requirements_file_path }}"
    src: files/requirements_galaxy.yml
    owner: root
    group: root
    mode: 0644

- name: Install collections from Ansible Galaxy
  command: "ansible-galaxy collection install {{ item }}"
  with_items: "{{ ansible_collections }}"

- name: Install roles from Ansible Galaxy
  command: "ansible-galaxy install -r {{ galaxy_requirements_file_path }}"

- name: Remove galaxy requirements file
  ansible.builtin.file:
    path: "{{ galaxy_requirements_file_path }}"
    state: absent
