---
- name: Install Jenkins server
  hosts: jenkins-server
  become: true
  roles:
    - geerlingguy.jenkins

- name: "Post-Install Setup"
  hosts: jenkins-server
  become: true
  tasks:
  - name: Add jenkins service to firewall
    firewalld:
      zone: public
      service: "jenkins"
      state: enabled
      immediate: true
      permanent: true
