---
- name: Install Gitea requiered roles from Ansible Galaxy
  hosts: gitea-server
  tasks:
  - name: Install Gitea role from Ansible Galaxy
    shell: "ansible-galaxy install thomas_maurice.ansible_role_gitea"

- name: Install Gitea requiered roles from Ansible Galaxy
  hosts: postgres-master
  become: true
  become_user: postgres
  tasks:
  - name: "Setup postgres Gitea Database"
    postgresql_db:
      state: present
      name: "{{ gitea_db_name }}"

  - name: "Create Gitea db user"
    postgresql_user:
      state: present
      name: "{{ gitea_db_user }}"
      password: "{{ gitea_db_password }}"

  - name: "Grant Gitea db user access to app db"
    postgresql_privs:
      type: database
      database: "{{ gitea_db_name }}"
      roles: "{{ gitea_db_user }}"
      grant_option: false
      privs: all

  - name: "Allow md5 connection for the db user"
    postgresql_pg_hba:
      dest: "~/data/pg_hba.conf"
      contype: host
      databases: all
      method: md5
      users: "{{ gitea_db_user }}"
      create: true

  - name: restart postgres
    ansible.builtin.systemd:
      name: postgresql 
      state: restarted

- name: "Install gitea"
  hosts: gitea-server
  roles:
    - gitea
